### ISSUE TITLE
clang incompatibility with tr1/memory

### ISSUE THREAD

**Issue by mzanon** [acado/acado#107]
This line
```c++
#include <tr1/memory>
```
causes a build error (tr1/memory not found) on this clang version:
```
fp-192-52-25-70:build mzanon$ clang --version
Apple LLVM version 5.1 (clang-503.0.40) (based on LLVM 3.4svn)
Target: x86_64-apple-darwin13.3.0
Thread model: posix
```
Acado shouldn't be compatabile with every single compiler, but this is the default OSX compiler so maybe it should get special preference.

**Comment by rienq** [comment]
Apparently, this issue returned to us.. @mzanon is having problems with following recent version of Clang on Mac OS X:

Apple LLVM version 6.1.0 (clang-602.0.49) (based on LLVM 3.6.0svn)
Target: x86_64-apple-darwin14.3.0
Thread model: posix

- When setting the flag "-stdlib=libc++", he gets the error
Error: <tr1/memory> file does not exist
and apprently, setting the extra option "-std=c++11" does not help (anymore)

- When alternatively setting the flag "-stdlib=libstdc++", he gets the errors:
error: no member named 'forward' in namespace 'std'
      ::new(p) T(std::forward<Args>(args)...);

**Comment by rienq** [comment]
This should be fixed now, let me know if things still wouldn't work with a certain platform-compiler combination..
