### ISSUE TITLE
#11 Bug in getDependencyPattern (Expression class)

### ISSUE THREAD

**Issue by ghorn** [acado/acado#11]
Milestone: 1.0 Status: open Owner: Rien Quirynen Labels: None
Updated: 2013-01-29 Created: 2013-01-29 Creator: Rien Quirynen Private: No

This function wants to give a matrix that tells you if a certain row in the expression depends on a certain variable (the element is different from zero)
or not (the element is equal to zero).
However, it does this by differentiation and then evaluating the resulting expressions by setting all the variables to zero.
This of course does not always work, e.g. x^2 --> derivative = 2*x --> result = 0.0 after evaluation at x = 0
(solved temporarily in revision 145)

**Comment by rienq** [comment]
fixed
