### ISSUE TITLE
Compiler errors under MSVS

### ISSUE THREAD

**Issue by mkatliar** [acado/acado#111]
For example, in examples_integrator/getting_started_discretized.cpp, line 55:
f << next(x) == x - h_x + h_u*u;

produces error:
1>C:\Program Files (x86)\Microsoft Visual Studio 11.0\VC\include\xutility(364): error C2039: 'iterator_category' : is not a member of 'ACADO::DifferentialState'
1>          D:\mkatliar\Documents\WABS\acado\include\acado/symbolic_expression/differential_state.hpp(56) : see declaration of 'ACADO::DifferentialState'
1>          ....\examples\integrator\getting_started_discretized.cpp(55) : see reference to class template instantiation 'std::iterator_traits<_Iter>' being compiled
1>          with
1>          [
1>              _Iter=ACADO::DifferentialState
1>          ]

It appears that next(x) is resolved to std::next<_FwdIt>(_FwdIt) instead of ::next( const ACADO::Expression& arg ).

Workaround:
change next(x) to ::next(x).

Investigation:
What is weird is that std::next() is for some reason exported to the :: namespace. There are  3 headers in the project, which do "using namespace std":
acado/modeling_tools/frame.hpp, line 39
acado/modeling_tools/kinvec.hpp, line 42
acado/code_generation/linear_solvers/linear_solver_export.hpp, line 48

If one of these files is includes, directly or indirectly, all names from std:: are exported to the root namespace. This can create inconveniences.

Proposed solution:
Remove "using namespace std" lines from the headers. Removing it from frame.hpp and kinvec.hpp does not have any adverse effects on compilation (not sure what are they for there). Removing the line from linear_solver_export.hpp requires changing "stringstream" to "std::stringstream" in the following files:
include\acado\code_generation\linear_solvers\gaussian_elimination_export.hpp
include\acado\code_generation\linear_solvers\householder_qr_export.hpp
include\acado\code_generation\linear_solvers\linear_solver_export.hpp
src\code_generation\linear_solvers\gaussian_elimination_export.cpp
src\code_generation\linear_solvers\householder_qr_export.cpp

After this, the project successfully builds under MSVC. 
It also removes the std:: names from the root namespace, which can be problematic if this is not wanted by the user of the ACADO library.

**Comment by mkotlyar** [comment]
Built the MATLAB interface with MSVC and it worked. Thanks for fixing!
