### ISSUE TITLE
MPC with Matrices

### ISSUE THREAD

**Issue by phyatt16** [acado/acado#128]
I'm trying to use acado to optimize the input of a dynamic system, but I would really like to use a matrix to define my inputs instead of defining tons of differential equations. How can I make acado understand that my control input is a matrix? Right now I define my inputs like this:

Control q_des;

and my differential equation like this:

f = acado.DiscretizedDifferentialEquation(h);
    
f.add(next(qd) == A1*qd+A2*q+B1*q_des); 
f.add(next(q) == A3*qd+A4*q+B2*q_des);

but it throws an error on the first "f.add" line because it says the dimensions don't agree. They would if it understood that q_des should be a 2x1 matrix. How do I define it like that?

**Comment by rienq** [comment]
Hi there,

I suppose what you are looking for is a definition like this:

Control q_des( "", 2, 1 );

where the first argument is the name, the second is the number of rows and the third is the number of columns.

**Comment by phyatt16** [comment]
Thanks for the response, but that doesn't seem to work for me. I have tried:
Control q_des("",2,1)
Control q_des("foo",2,1)
and many other variations. The closest I seem to get is with the error message:

For colon operator with char operands, first and last operands must be
char.

Error in Control (line 43)
        for i = 1:N

or this error message:

At compilation, "var" was determined to be a variable and this variable
is uninitialized. "var" is also a function name and previous versions
of MATLAB would have called the function. However, MATLAB 7 forbids the
use of the same name in the same context as both a function and a
variable.

Error in Control (line 59)
        assignin( 'caller', name, var );

**Comment by phyatt16** [comment]
Also, because I cannot find related documentation or questions:

Can I use Matlab to produce a script for MPC? I want to be able to change the initial conditions and some other parameters and solve again without having to recompile a new c++ file every time. Some documentation refers to ExportVariable and mpc.exportCode(), but I can't find these in Matlab. How can I create variables that I can change and then pass into my already generated code?

**Comment by rienq** [comment]
Ow I see, you didn't mention before that you were using the MATLAB interface so I gave you the C++ syntax.
In MATLAB, you can use the following simplified syntax:

Control q_des(2,1);

make sure you do not use any whitespaces in the definition of this control as it is calling a script based on the string "q_des(2,1)". The error message you mentioned is unexpected though, since I receive something else when I use the C++ syntax in MATLAB.

Regarding constants in auto generated code, there is the option to use an OnlineData definition:

OnlineData p; % some parameter you can use in the model formulation

The initial condition is always a parameter by default since that is necessary to implement NMPC.
It would by the way be better to pose these kind of questions on our discussion forum where this could help other users as well, since our documentation is indeed quite limited because of the project being open source and maintained rather occasionally by very few people.

**Comment by phyatt16** [comment]
Thanks - I have asked another question on the forum. You guys are tops.

-Phil

**Comment by phyatt16** [comment]
These were the questions I posted, just in case the context of our previous
correspondence may help.




I am trying to produce an MPC optimization for a multi-link robot arm with
Matlab. It worked ok when I wrote up each equation for every joint, but now
that I have incorporated matrices I get the error "Error using isempty"
when it tries to compile c++ code.

The full error and my acado code is found below.

Also - the online data definition function is not recognized in matlab. I
have tried:

OnlineData beta;

but I receive the error:

Undefined function 'OnlineData' for input arguments of type
'char'.

*The Error:*
Error using isempty
Too many input arguments.

Error in acado.Variable/toString (line 44)
            if isempty(obj.value)

Error in acado.Function/getInstructions (line 38)
            fprintf(cppobj.fileMEX,sprintf('    %s << %s;\n', obj.name,
obj.items{i}{1}.toString));


Error in acado.AcadoMatlab/generateCPP (line 83)
           obj.instructionList{i}.getInstructions(obj, 'FB'); % first body
elements


Error in GEN_ACADO (line 41)
ACADO_.helper.generateCPP();

Error in END_ACADO (line 35)
GEN_ACADO;


Error in optimization_comparison_acado_matrices (line 82)
END_ACADO;


*My Code:*
BEGIN_ACADO;                                % Always start with
"BEGIN_ACADO".

    acadoSet('problemname', 'robot' );

    DifferentialState qd(2,1);                      % Velocity
    DifferentialState q(2,1);                       % position
    acado.Matrix(A1);
    acado.Matrix(A2);
    acado.Matrix(A3);
    acado.Matrix(A4);
    acado.Matrix(B1);
    acado.Matrix(B2);

    Control q_des(2,1);                             % Control input
    h = 0.002;

    %% Differential Equation
    f = acado.DiscretizedDifferentialEquation(h);   % Set the differential
equation object
    f.add(next(qd) == A1*qd+A2*q+B1*q_des);
    f.add(next(q) == A3*qd+A4*q+B2*q_des);

    %% Optimal Control Problem
    ocp = acado.OCP(0,1);         % Set up the Optimal Control Problem (OCP)

    s=[alpha,0;
        0,alpha];
    h={q};
    r=q_goal;
    ocp.minimizeLSQ(s,h,r);

    s=[beta,0;
        0,beta];
    m={qd};
    r=[0;0];
    ocp.minimizeLSQEndTerm(s,m,r);

    s=[gamma,0;
        0,gamma];
    m={q};
    r=q_goal;
    ocp.minimizeLSQEndTerm(s,m,r);

    ocp.subjectTo(f);                                       % Optimize with
respect to your differential equation
    ocp.subjectTo('AT_START',q==q0');                       %first joint
initial position
    ocp.subjectTo('AT_START',qd==q_d0');                    %first joint
initial velocity
    ocp.subjectTo(-q_d_max<=qd<=q_d_max);                   %second joint
max velocity
    ocp.subjectTo(-tau_max<=(kp*(q_des-q)-kd*qd)<=tau_max); %first joint
max torque

    %% Optimization Algorithm
    algo =acado.OptimizationAlgorithm(ocp); % Set up the optimization
algorithm, link it to your OCP
    %algo.set( 'HESSIAN_APPROXIMATION', 'EXACT_HESSIAN' );
END_ACADO;

**Comment by rienq** [comment]
You can pull the latest stable branch for the OnlineData functionality by the way..
