### ISSUE TITLE
Matlab interface compiles successfully but information on iterations is not displayed

### ISSUE THREAD

**Issue by remusmp** [acado/acado#133]
I just cloned the stable branch and ran 'make' for the Matlab interface. Everything worked fine: no errors nor warnings. Someone however told me that I should see iteration information while running a file and I cannot find the way to display that. Any hints?

Windows machine x64
Matlab 2014b
Microsoft Visual C++ 2013 Professional

**Comment by remusmp** [comment]
There is a MexVerbose option somewhere in the code and I switched it to 1, then rebuilt everything but it didn't work.

**Comment by rienq** [comment]
I suppose this issue is related to #145
