### ISSUE TITLE
Doing regularization in the context of least squares objective function

### ISSUE THREAD

**Issue by m1360** [acado/acado#137]
Hi,
I am fitting my states to the measurements using least squares objective function in offline optimization in Acado.  I get very noisy and instable controls. So, I want to do a kind of regularization in this context to get a stable and smoother controls. How could I do this regularization in Acado?

Thanks

Maedeh

**Comment by mvukov** [comment]
-> [forum](http://sourceforge.net/p/acado/discussion/).
