### ISSUE TITLE
Accessing disturbance variable in generated code

### ISSUE THREAD

**Issue by ozymandias90** [acado/acado#150]
Hi, 

My question is with regards to the generated code. I formulated my NMPC problem in ACADO, and exported the code. Using the exported code, I run real time iterations in which I feed the current measurements and the reference values from my experimental setup into the variables acadoVariables.y and acadoVariables.x0. ACADO generates the control for the next interval which I feed back into my experimental setup. This setup is working extremely well given that the system sampling time is of the order of ~100 ms.

To improve the performance I wanted to modify my system model to incorporate a disturbance R1 and R2 as shown below.

DifferentialState x,y;
Control u;
Disturbance R1, R2;
f << dot( x ) ==  x/(x^2+y^2)*u+R1;
f << dot( y ) ==  y/(x^2+y^2)*u+R2;

The optimal control formulation is the same as before (least squares tracking objective with end term). R1 and R2 are disturbance variables that I measure experimentally in real time.

Now my question is - I am calculating the disturbances R1 and R2 external to the exported code, and wanted to pass those variables to acado during the real time iterations loop. However, I was not able to figure out which variables to feed them into since acado_common.h did not define variables to accept the disturbance values. For example, I can feed the measurement values to acadoVariables.y - is there a similar variable that I can use for disturbance data?

Can you help me out?

Thanks!
Abhi

**Comment by rienq** [comment]
Dear Abhi,

Disturbance variables are indeed not accepted in the ACADO code generation tool. Instead, you can use OnlineData variables for your purpose so the code would look:

<code>DifferentialState x,y;
Control u;
OnlineData R1, R2;
f << dot( x ) == x/(x^2+y^2)u+R1;
f << dot( y ) == y/(x^2+y^2)u+R2;</code>

I hope this can help you further.

Best,
Rien

**Comment by ozymandias90** [comment]
Thanks a lot, Rien! This certainly helps - I think I can figure out how to implement the disturbances. My apologies for posting the question on the issue tracker.

Abhi

**Comment by rienq** [comment]
no problem, of course! glad I could help.. ;-)
