### ISSUE TITLE
Error code generation with exact hessian with onlinedata objects

### ISSUE THREAD

**Issue by nielsvd** [acado/acado#155]
Generating code with "HESSIAN_APPROXIMATION, EXACT_HESSIAN" works fine without OnlineData objects. As soon as those appear in the OCP definition, the following error is thrown by ACADO at code generation runtime:

    [ACADO] Error: Incompatible vector dimensions
      Code: (RET_VECTOR_DIMENSION_MISMATCH) 
      File: /home/niels/Documents/GIT/acadotoolkit-master/acado/code_generation/export_arithmetic_statement.cpp
      Line: 561

    [ACADO] Error: Unable to export statement due to incomplete definition
      Code: (RET_UNABLE_TO_EXPORT_STATEMENT) 
      File: /home/niels/Documents/GIT/acadotoolkit-master/acado/code_generation/export_statement_block.cpp
      Line: 282

It can be reproduced as follows, take the kite empc example: 
*acado-toolkit/examples/code_generation/empc/powerkite.cpp*

And make the changes:

    @@ -283,13 +283,13 @@
                          + 2.5e6 * dtheta  * dtheta;
     //                   ---------------------------
     
    -
    +OnlineData test_object;
     
     // THE "RIGHT-HAND-SIDE" OF THE ODE:
     // ---------------------------------------------------------------
        DifferentialEquation f;
     
    -   f  << dot(r)      ==  dr                             ;
    +   f  << dot(r)      ==  dr + 1e-5*test_object          ;
        f  << dot(phi)    ==  dphi                           ;
        f  << dot(theta)  ==  dtheta                         ;
        f  << dot(dr)     ==  ddr0                           ;

ACADO revision (master branch): e86375285cb0d288f66a6e85ff6b891eddd9ca6b

**Comment by rienq** [comment]
I am sorry for the delay on this, but it was a stupid bug which should be fixed by the commit referenced above.. let me know in case the issue would still remain ! Cheers
