### ISSUE TITLE
Windows installation with Visual Studio - works only with VS2010 and .NET 4

### ISSUE THREAD

**Issue by chintanp** [acado/acado#168]
I tried with VS 2015 and .NET framework 4.5 and 4.6, and ACADOtoolkit setup gives lot of errors even before the build process begins. Also, the matlab interface doesnt work with VS 2012. 

The only configuration that works successfully is Visual Studio / Express 2010 with .NET framework 4.0. I had to un-install new versions of .NET framework other 4.0 cant be installed. I think the install docs need to be updated to reflect this change and save the new-comers from un-necessary heartburn. 

If someone else can confirm, then I will make a PR.

**Comment by rienq** [comment]
Thanks a lot for this information! It is however definitely a pity to hear about these compilation errors with the newer versions of VS and .NET

But I will keep this in mind and, if other Windows users can confirm this, I will also update our documentation (personally, I cannot check this on my system). Thanks again!
