### ISSUE TITLE
Compilation failed in ACADO with Forces

### ISSUE THREAD

**Issue by chenyutao36** [acado/acado#178]
According to the manual, the QP solver Forces is supported in ACADO and the only modification of the code generation is to set

mpc.set( 'SPARSE_QP_SOLUTION',          'SPARSE_SOLVER');
mpc.set( 'QP_SOLVER',                   'QP_FORCES'    	);

The forces code is successfully generated from the server as well as the mex interface.
However, when compiling the code I get the following error

Error using mex
acado_solver.c
...\forces\acado_solver.c(876) : error C2198: 'forces_solve' : too few arguments for call

Error in make_acado_solver (line 81)
eval( sprintf(CGRecipe, fileOut, mexext) );

BTW, I'm using the latest version of Forces Pro.

Can someone solve this problem?

**Comment by rienq** [comment]
This should be fixed in the latest master branch, is it not?

**Comment by chenyutao36** [comment]
Yes, this single problem is fixed
