### ISSUE TITLE
ACADO-- interfaces of MATLAB in ubuntu

### ISSUE THREAD

**Issue by lijq92** [acado/acado#225]
I have a question about using ACADO tools in the interfaces of MATLAB in ubuntu, mainly about the installation. Now I installed the matlab2015b with gcc-4.7.4 and g++- 5.4.1, I can make ACADO successfully. But I cannot run the example. The warning is 

Warning: You are using gcc version '5.4.1'. The version of gcc
is not supported. The version currently supported with MEX is
'4.7.x'. For a list of currently supported compilers see:
http://www.mathworks.com/support/compilers/current_release. 

But I am sure the current version of gcc is 4.7.4. It is very strange.
May the problem be the inner port of gcc is default 5.4.1? Could you give me some advice?

**Comment by rienq** [comment]
https://www.mathworks.com/matlabcentral/answers/137228-setup-mex-compiler-for-r2014a-for-linux
