### ISSUE TITLE
How to correct use OnlineData in Codegeneration for SIMULINK-Envoirment

### ISSUE THREAD

**Issue by FeiZ666** [acado/acado#251]
Hello everyone, I would like to use OnlineData in CodeGeneration to define parameters other than State and Control that will be used to describe State's equation ocp.setModel (f) and use it as a real-time signal in simulink. Is this OnlineData Correct usage? Thank you for your reply and help @roryyorke @jgillis @tibnor @olzhas @ghorn

**Comment by rienq** [comment]
Yes, that's what it is supposed to be used for.
