### ISSUE TITLE
Can't find acado_code_generation.hpp - Fatal error

### ISSUE THREAD

**Issue by guiaugustoga987** [acado/acado#275]
Hi,

I'm new to ACADO so I just followed the installation tutorial (https://acado.github.io/install_linux.html) and was able to open the example simple_ocp.

Then I tried to compile a c++ file to use the code generation to solve a MPC problem. But every c++ I tried it got an error (couldn't find acado_code_generation.hpp). it says the file does not exist, even though it is located in ACADOtoolkit/acado folder.

What do I need to do to be able to compile my source file ?

Thanks.

**Comment by ChaoqinRobotics** [comment]
My solution is append source <ACADO_ROOT>/build/acado_env.sh into your bashrc file and then source it, as shown in https://acado.github.io/using_cmake_unix_common.html
